[2024-07-19T08:13:59.098+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crawling_dag_v2.read_s3_and_add_size_color manual__2024-07-19T08:02:28.132053+00:00 [queued]>
[2024-07-19T08:13:59.108+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crawling_dag_v2.read_s3_and_add_size_color manual__2024-07-19T08:02:28.132053+00:00 [queued]>
[2024-07-19T08:13:59.109+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-07-19T08:13:59.130+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): read_s3_and_add_size_color> on 2024-07-19 08:02:28.132053+00:00
[2024-07-19T08:13:59.135+0000] {standard_task_runner.py:60} INFO - Started process 969 to run task
[2024-07-19T08:13:59.141+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'crawling_dag_v2', 'read_s3_and_add_size_color', 'manual__2024-07-19T08:02:28.132053+00:00', '--job-id', '459', '--raw', '--subdir', 'DAGS_FOLDER/musinsa_dag.py', '--cfg-path', '/tmp/tmpwksr4ryd']
[2024-07-19T08:13:59.144+0000] {standard_task_runner.py:88} INFO - Job 459: Subtask read_s3_and_add_size_color
[2024-07-19T08:13:59.195+0000] {task_command.py:423} INFO - Running <TaskInstance: crawling_dag_v2.read_s3_and_add_size_color manual__2024-07-19T08:02:28.132053+00:00 [running]> on host 9a455ef6c02c
[2024-07-19T08:13:59.298+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crawling_dag_v2' AIRFLOW_CTX_TASK_ID='read_s3_and_add_size_color' AIRFLOW_CTX_EXECUTION_DATE='2024-07-19T08:02:28.132053+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-19T08:02:28.132053+00:00'
[2024-07-19T08:13:59.314+0000] {base.py:83} INFO - Using connection ID 'aws_s3' for task execution.
[2024-07-19T08:13:59.315+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3', conn_type='aws') credentials retrieved from login and password.
[2024-07-19T08:15:22.221+0000] {logging_mixin.py:188} INFO - Visited: https://www.musinsa.com/app/goods/1191407
[2024-07-19T08:15:23.706+0000] {logging_mixin.py:188} INFO - Clicked button at div[36] on https://www.musinsa.com/app/goods/1191407
[2024-07-19T08:15:24.898+0000] {logging_mixin.py:188} INFO - Element click intercepted on https://www.musinsa.com/app/goods/1191407 at div[36], trying next element.
[2024-07-19T08:15:25.999+0000] {logging_mixin.py:188} INFO - Failed to visit https://www.musinsa.com/app/goods/1191407 due to Message: element not interactable
  (Session info: chrome-headless-shell=126.0.6478.114)
Stacktrace:
#0 0x5588adbb169a <unknown>
#1 0x5588ad893f21 <unknown>
#2 0x5588ad8e1abf <unknown>
#3 0x5588ad8d540f <unknown>
#4 0x5588ad903872 <unknown>
#5 0x5588ad8d4d89 <unknown>
#6 0x5588ad903a3e <unknown>
#7 0x5588ad9225c3 <unknown>
#8 0x5588ad903613 <unknown>
#9 0x5588ad8d34f7 <unknown>
#10 0x5588ad8d3e4e <unknown>
#11 0x5588adb7786b <unknown>
#12 0x5588adb7b911 <unknown>
#13 0x5588adb6335e <unknown>
#14 0x5588adb7c472 <unknown>
#15 0x5588adb47cbf <unknown>
#16 0x5588adba1098 <unknown>
#17 0x5588adba1270 <unknown>
#18 0x5588adbb07cc <unknown>
#19 0x7fee5734cac3 <unknown>
[2024-07-19T08:17:48.327+0000] {logging_mixin.py:188} INFO - Visited: https://www.musinsa.com/app/goods/1599217
[2024-07-19T08:17:50.664+0000] {logging_mixin.py:188} INFO - Element click intercepted on https://www.musinsa.com/app/goods/1599217 at div[36], trying next element.
[2024-07-19T08:17:50.845+0000] {logging_mixin.py:188} INFO - No button found on https://www.musinsa.com/app/goods/1599217
[2024-07-19T08:18:11.959+0000] {logging_mixin.py:188} INFO - Visited: https://www.musinsa.com/app/goods/2139143
[2024-07-19T08:18:14.459+0000] {logging_mixin.py:188} INFO - Element click intercepted on https://www.musinsa.com/app/goods/2139143 at div[35], trying next element.
[2024-07-19T08:18:14.708+0000] {logging_mixin.py:188} INFO - No button found on https://www.musinsa.com/app/goods/2139143
[2024-07-19T08:18:16.138+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-07-19T08:18:16.143+0000] {process_utils.py:131} INFO - Sending 15 to group 969. PIDs of all processes in the group: [969]
[2024-07-19T08:18:16.144+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 969
[2024-07-19T08:18:16.145+0000] {taskinstance.py:2483} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-07-19T08:18:16.198+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=969, status='terminated', exitcode=0, started='08:13:58') (969) terminated with exit code 0
