[2024-07-20T04:38:38.652+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: crawling_dag_v2.read_s3_and_add_size_color manual__2024-07-19T08:28:04.384571+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
